package serializers.internal

import serializers._

object GithubIdSerializers extends InternalSerializerFormat
with generic.GithubIdSerializers

object GithubSerializers extends InternalSerializerFormat
with generic.GithubIdSerializers
